-- Insert Data into Menu Table
INSERT INTO MENU  VALUES (1, 'Dosa', 35);
INSERT INTO MENU VALUES (2, 'Rice', 45);
INSERT INTO MENU VALUES (3, 'Roti', 30);
INSERT INTO MENU VALUES (4, 'Jira Rice', 60);
INSERT INTO MENU VALUES (5, 'Dal', 90);

-- Insert Data into User Table
INSERT INTO USERS VALUES ('ram', 'USER', TRUE, '$2a$10$CEowIBoP73DKZf./TVVLqO.Z2034Rk717xxfecnvxyt8HHVFLLe0a');
INSERT INTO USERS VALUES ('suresh', 'ADMIN', TRUE, '$2a$10$KzQAQ4kAjSBsd.0MiHgyAecxwhj8MZrqju3FcjGrVn0TxWz563Qta');
INSERT INTO USERS VALUES ('mohan', 'ADMIN', TRUE, '$2a$10$2mT8yco7eGGm/dtUsQffLOXME5aq5sYR9JJpG6xTOtuXGePIBPhUS');

-- Insert Data into Invoice Table
--INSERT INTO ORDERS VALUES (1, CURRENT_TIMESTAMP,'ram');
--INSERT INTO ORDERS VALUES (2, CURRENT_TIMESTAMP,'ram');
--INSERT INTO INVOICE VALUES (1, CURRENT_TIMESTAMP,'ram');
---INSERT INTO INVOICE VALUES (2, CURRENT_TIMESTAMP,'suresh');

-- Insert Data into Order Table
--INSERT INTO ORDER_DETAILS VALUES (1,4,500,1,1);
--INSERT INTO ORDER_DETAILS VALUES (2,2,600,2,1);

