package com.surabi.restaurants.config;

import com.surabi.restaurants.entity.AuditLog;
import com.surabi.restaurants.repository.AuditRepository;
import com.surabi.restaurants.serviceimpl.UserLoggedDetailsImpl;
import lombok.extern.slf4j.Slf4j;
import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.AfterReturning;
import org.aspectj.lang.annotation.Aspect;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;

import java.util.Date;

@Slf4j
@Aspect
@Configuration
public class AspectConfig {

    @Autowired
    AuditRepository auditRepository;

	/*@Around("execution(public * com.surabi.restaurants.serviceimpl.*.*(..) )")
	public void logBeforeAndAfterAllMethods(ProceedingJoinPoint proceedingJoinPoint) throws Throwable {
		log.info(proceedingJoinPoint.getSignature().getName() + " Started");
		proceedingJoinPoint.proceed();
		log.info(proceedingJoinPoint.getSignature().getName() + " Ended");
	}*/

    @AfterReturning("execution(public * com.surabi.restaurants.serviceimpl.RestaurantServiceImpl.checkOut(..) )")
    public void logBeforeAddBill(JoinPoint joinPoint) {
        auditRepository.saveAndFlush(AuditLog.builder().createDate(new Date()).user_created(UserLoggedDetailsImpl.getMyDetails())
                .discription("Bill " + joinPoint.getArgs()[0] + " generated by User").build());
    }

    @AfterReturning("execution(public * com.surabi.restaurants.serviceimpl.AdminServiceImpl.CreateUser(..) )")
    public void logBeforeAddUser(JoinPoint joinPoint) {
        auditRepository.saveAndFlush(AuditLog.builder().createDate(new Date()).user_created(UserLoggedDetailsImpl.getMyDetails())
                .discription("Created user by admin ").build());
    }

    @AfterReturning("execution(public * com.surabi.restaurants.serviceimpl.AdminServiceImpl.deleteUser(..) )")
    public void logBeforeDeteleUser(JoinPoint joinPoint) {
        auditRepository.saveAndFlush(AuditLog.builder().createDate(new Date()).user_created(UserLoggedDetailsImpl.getMyDetails())
                .discription("Deleted user by admin ").build());
    }

    @AfterReturning("execution(public * com.surabi.restaurants.serviceimpl.AdminServiceImpl.UpdateUser(..) )")
    public void logBeforeUpdateUser(JoinPoint joinPoint) {
        auditRepository.saveAndFlush(AuditLog.builder().createDate(new Date()).user_created(UserLoggedDetailsImpl.getMyDetails())
                .discription("Updated user by admin ").build());
    }

/*	@AfterReturning("execution(public * com.surabi.restaurants.serviceimpl.UserServiceImpl.save(..) )")
	public void logBeforeAddUserReg(JoinPoint joinPoint) {
		auditRepository.saveAndFlush(AuditLog.builder().createDate(new Date()).user(UserLoggedDetailsImpl.getMyDetails())
				.discription("User added using registration ").build());
	}*/
}
